RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = ws2812

OLED_ENABLE = yes
OLED_DRIVER_ENABLE = yes
OLED_DRIVER = ssd1306

VIA_ENABLE = yes
VIAL_ENABLE = yes
DEBUG_ENABLE = yes

WS2812_DRIVER = vendor
SERIAL_DRIVER = vendor

WPM_ENABLE = yes
